/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Faucet_V1__factory } from "./Faucet_V1__factory";
export { IFaucet__factory } from "./IFaucet__factory";
