/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { default as XGDAOQueries } from "./XGDAOQueries";
export { default as SGDAOQueries } from "./SGDAOQueries";
export { default as GDAOQueries } from "./GDAOQueries";
export { default as ERC20Queries } from "./ERC20Queries";
