/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DeployRoles__factory } from "./DeployRoles__factory";
export { RolesDeploy__factory } from "./RolesDeploy__factory";
